### ISSUE TITLE
Fail to import pythonwhois in my python application 

### ISSUE THREAD

**Issue by mdagcilar** [joepie91/python-whois#103]
Sorry i'm new to python. 
I've done 'pip install pythonwhois' my current verison is - pythonwhois-2.4.3-py2.7.egg

Then i've written this python script to just do a WHOis lookup on "www.google.com" 

I get this error running the script:
AttributeError: 'module' object has no attribute 'get_whois' 

It's not finding the get_whois function from the library. What am i missing?

*****_code**_****

import pythonwhois

domain = "www.google.com"
normalized = True

pythonwhois.get_whois(domain, True)

**Comment by joepie91** [comment]
What version of pythonwhois are you using? The `get_whois` method was only [introduced in 2.x](http://cryto.net/pythonwhois/upgrade.html), so it's possible that you're using an outdated version.

**Comment by mdagcilar** [comment]
Thanks for your quick response. I'm using pythonwhois-2.4.3-py2.7.egg 

Any other suggestions why this couldn't be working?

**Comment by joepie91** [comment]
That's odd. Can you run the following code in a Python REPL (just run `python` without a script name) and post the output here?

``` python
import pythonwhois
print pythonwhois
print pythonwhois.get_whois
```

**Comment by mdagcilar** [comment]
I guess this is the output that you expected, this seems to work. Why doesn't my python script not recognize the function inherited from the pythonwhois module? I'm on a windows 8 machine, and my script is just located on my desktop..

![pythonwhois](https://cloud.githubusercontent.com/assets/6627550/11374241/f427c8ac-92cc-11e5-9445-9a42fa121793.png)

**Comment by mdagcilar** [comment]
follow up on this please? Still having this issue

**Comment by mdagcilar** [comment]
fixed the issue. The problem was where the file was located, the .py file on my desktop was causing issues with python. The same code compiles in a different directory

**Comment by joepie91** [comment]
Huh, that's odd. What did your directory structure look like, and what file(s) was/were interfering?  I'm curious whether it's a Python issue or something specific to pythonwhois.
