### ISSUE TITLE
No WHOIS server for .ps TLD

### ISSUE THREAD

**Issue by iakat** [joepie91/python-whois#15]
> echo whois; whois v.ps; echo pwhois;./pwhois v.ps;echo pls fix
> whois
> Domain Name: v.ps
> Domain Status: Available
> Notes: This name is not allowed by the policy of this registry, and can not be registered
> 
> TERMS OF USE: You are not authorized to access or query our Whois
> database through the use of electronic processes that are high-volume and
> automated.  Whois database is provided by PNINA as a service to the internet
> community on behalf of PNINA and Its Certified Registrars (CR). (http://www.pnina.ps/registrars/registrars-list/)
> 
> The data is for information purposes only. PNINA does not
> guarantee its accuracy. By submitting a Whois query, you agree to abide
> by the following terms of use: You agree that you may use this Data only
> for lawful purposes and that under no circumstances will you use this Data
> to: (1) allow, enable, or otherwise support the transmission of mass
> unsolicited, commercial advertising or solicitations via e-mail, telephone,
> or facsimile; or (2) enable high volume, automated, electronic processes
> that apply to PNINA and it's Certified Registrar's (or PNINA or CR computer systems). The
> compilation, repackaging, dissemination or other use of this Data is
> expressly prohibited.
> 
> Last update of WHOIS database: 2014-05-22T15:18:54.252Z <<<
> pwhois
> Traceback (most recent call last):
>   File "./pwhois", line 23, in <module>
>     data = pythonwhois.net.get_whois_raw(args.domain[0])
>   File "/tmp/python-whois/pythonwhois/net.py", line 12, in get_whois_raw
>     target_server = get_root_server(domain)
>   File "/tmp/python-whois/pythonwhois/net.py", line 48, in get_root_server
>     raise shared.WhoisException("No root WHOIS server found for TLD.")
> pythonwhois.shared.WhoisException: No root WHOIS server found for TLD.
> pls fix

**Comment by joepie91** [comment]
Fixed and pushed as a new version. Update with `pip install --upgrade pythonwhois`.
