### ISSUE TITLE
Unable to get whois record for .ac.uk domains

### ISSUE THREAD

**Issue by richard-jones** [joepie91/python-whois#16]
Attempted to pull whois record for UK HE institutions as follows (for example):

```
pythonwhois.get_whois("imperial.ac.uk")
```

This responds with the whois record for "ac.uk" not "imperial.ac.uk".  From the response data:

```
Domain name:\r\n        ac.uk
```

I guess you require explicit lists of supported extensions?

**Comment by joepie91** [comment]
Hmm. It looks like `whois.iana.org` is returning the `.uk` server as root WHOIS server, rather than the `.ac.uk` server. Since the `.uk` WHOIS server doesn't provide a redirect, that's where pythonwhois gives up. I'll have a look to see how this can be solved.

**Comment by joepie91** [comment]
Yup. The correct WHOIS data for `imperial.ac.uk` is served by `whois.ja.net`, not by `whois.nic.uk` as IANA suggests. I suspect I'll have to hardcode an exception for this.

Do you happen to know of any other `.uk` sub-TLDs that have this problem?

**Comment by richard-jones** [comment]
I don't, I'm afraid, that's the only one I've played with.  Could try
gov.ukas another obvious one, but it makes sense that
ac.uk is handled by janet as a special case, and I'm not sure there are any
others with a similar status

But, I'm pretty clueless about whois, tbh, hence pleased to find your
python module :)

On 23 May 2014 14:20, Sven Slootweg notifications@github.com wrote:

> Yup. The correct WHOIS data for imperial.ac.uk is served by whois.ja.net,
> not by whois.nic.uk as IANA suggests. I suspect I'll have to hardcode an
> exception for this.
> 
> Do you happen to know of any other .uk sub-TLDs that have this problem?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joepie91/python-whois/issues/16#issuecomment-44007554
> .

## 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by joepie91** [comment]
Currently working on fixing it; target WHOIS server exception is already fixed, as is registrant parsing (which deviates from Nominet format, for some reason). Currently working on the date format.

WHOIS data is generally a huge mess :) Even now I ran across one .ac.uk domain that simply doesn't provide anything other than "United Kingdom" for its address.

**Comment by richard-jones** [comment]
Yes, I'm discovering that.  There isn't that much consistency in the fields
you get back, which is making coding something that can extract, say,
addresses of host organisations a bit time consuming.  I don't suppose you
know a good primer/resource for finding out what kinds of fields are
generally available?  The wikipedia page is of minimal assistance!

On 23 May 2014 14:51, Sven Slootweg notifications@github.com wrote:

> Currently working on fixing it; target WHOIS server exception is already
> fixed, as is, registrant parsing (which deviates from Nominet format, for
> some reason). Currently working on the date format.
> 
> WHOIS data is generally a huge mess :) Even now I ran across one .ac.ukdomain that simply doesn't provide anything other than "United Kingdom" for
> its address.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joepie91/python-whois/issues/16#issuecomment-44010957
> .

## 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by joepie91** [comment]
Alright, this should be fixed now - I'll push a new version in a bit.

As for documentation... it basically doesn't exist. There are a few kind-of-standard WHOIS formats that have been adopted, but all of them are adopted with slight variations across registries, and in the end you basically end up with a complete lack of standardization. There's an XML-based data exchange format, but nobody actually uses that on a public-facing server as far as I can tell.

The WHOIS protocol itself really doesn't define anything more than "send query, get back response in _some_ kind of textual format". It doesn't mandate any particular data being available in that response, let alone a format for it. That's pretty much the problem I'm trying to solve with pythonwhois :)

**Comment by joepie91** [comment]
Pushed a new version with the fix. Update with `pip install --upgrade pythonwhois`.

I've also had a look at `.gov.uk` - those queries are sent to the correct server by IANA, but there were some parsing oddities (due to the absence of a region in the registrant address data). I have also resolved those.

**Comment by richard-jones** [comment]
Brilliant, thank you!

On 23 May 2014 17:17, Sven Slootweg notifications@github.com wrote:

> Pushed a new version with the fix. Update with pip install --upgrade
> pythonwhois.
> 
> I've also had a look at .gov.uk - those queries are sent to the correct
> server by IANA, but there were some parsing oddities (due to the absence of
> a region in the registrant address data). I have also resolved those.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joepie91/python-whois/issues/16#issuecomment-44031227
> .

## 

Richard Jones,

Founder, Cottage Labs
t: @richard_d_jones, @cottagelabs
w: http://cottagelabs.com

**Comment by joepie91** [comment]
You're welcome; feel free to open another issue if any more problems come up :)
