### ISSUE TITLE
Sina.com.cn does not parses registration date

### ISSUE THREAD

**Issue by techstroke** [joepie91/python-whois#19]
It cannot parse registration date for this domain I suspect other domains ending with .cn have same fate , although a cli WHOIS , shows registration date and in the below output you can see it in the 'raw' value but parser cannot find and only shows expiry date !

input: 
w = pythonwhois.get_whois("sina.com.cn")
pprint.pprint(w)

output:

{'contacts': {'admin': None,
              'billing': None,
              'registrant': None,
              'tech': None},
 'emails': ['domainname@staff.sina.com.cn'],
 'expiration_date': [datetime.datetime(2019, 12, 4, 9, 32, 35)],
 'nameservers': ['ns3.sina.com.cn',
                 'ns2.sina.com.cn',
                 'ns4.sina.com.cn',
                 'ns1.sina.com.cn'],
 'raw': ['Domain Name: sina.com.cn\nROID: 20021209s10011s00082127-cn\nDomain Status: clientDeleteProhibited\nDomain Status: serverDeleteProhibited\nDomain Status: clientUpdateProhibited\nDomain Status: serverUpdateProhibited\nDomain Status: clientTransferProhibited\nDomain Status: serverTransferProhibited\nRegistrant ID: sinacomcn2\nRegistrant: \xe5\x8c\x97\xe4\xba\xac\xe6\x96\xb0\xe6\xb5\xaa\xe4\xba\x92\xe8\x81\x94\xe4\xbf\xa1\xe6\x81\xaf\xe6\x9c\x8d\xe5\x8a\xa1\xe6\x9c\x89\xe9\x99\x90\xe5\x85\xac\xe5\x8f\xb8\nRegistrant Contact Email: domainname@staff.sina.com.cn\nSponsoring Registrar: \xe5\x8c\x97\xe4\xba\xac\xe6\x96\xb0\xe7\xbd\x91\xe6\x95\xb0\xe7\xa0\x81\xe4\xbf\xa1\xe6\x81\xaf\xe6\x8a\x80\xe6\x9c\xaf\xe6\x9c\x89\xe9\x99\x90\xe5\x85\xac\xe5\x8f\xb8\nName Server: ns3.sina.com.cn\nName Server: ns2.sina.com.cn\nName Server: ns4.sina.com.cn\nName Server: ns1.sina.com.cn\nRegistration Date: 1998-11-20 00:00:00\nExpiration Date: 2019-12-04 09:32:35\nDNSSEC: unsigned\n'],
 'registrar': ['\xe5\x8c\x97\xe4\xba\xac\xe6\x96\xb0\xe7\xbd\x91\xe6\x95\xb0\xe7\xa0\x81\xe4\xbf\xa1\xe6\x81\xaf\xe6\x8a\x80\xe6\x9c\xaf\xe6\x9c\x89\xe9\x99\x90\xe5\x85\xac\xe5\x8f\xb8'],
 'status': ['clientDeleteProhibited',
            'serverDeleteProhibited',
            'clientUpdateProhibited',
            'serverUpdateProhibited',
            'clientTransferProhibited',
            'serverTransferProhibited']}

**Comment by joepie91** [comment]
Confirmed, I can reproduce the problem. I'll have a look at it right away.

**Comment by joepie91** [comment]
Fixed in version 2.2.2. To upgrade, run `pip install --upgrade pythonwhois`.

**Comment by techstroke** [comment]
Thanks !! I'll upgrade right now
