### ISSUE TITLE
.it domains not parsed

### ISSUE THREAD

**Issue by tgianko** [joepie91/python-whois#21]
Hi there,

pythonwhois doesn't parse properly google.it and others (e.g., yahoo.it). I suspect it applies to all .it domains. 

Here is the test I've done so far:

it = pythonwhois.get_whois("google.it")
pprint(it)

{'contacts': {'admin': None,
              'billing': None,
              'registrant': None,
              'tech': None},
 'creation_date': [datetime.datetime(1999, 12, 10, 0, 0),
                   datetime.datetime(2013, 4, 21, 1, 5, 35)],
 'expiration_date': [datetime.datetime(2015, 4, 21, 0, 0)],
 'raw': ['\n********************************************************************_\n_ Please note that the following result could be a subgroup of      _\n_ the data contained in the database.                               _\n_                                                                   _\n_ Additional information can be visualized at:                      _\n_ http://www.nic.it/cgi-bin/Whois/whois.cgi                         *\n*********************************************************************\n\nDomain:             google.it\nStatus:             ok\nCreated:            1999-12-10 00:00:00\nLast Update:        2014-05-07 00:52:45\nExpire Date:        2015-04-21\n\nRegistrant\n  Name:             Google Ireland Holdings\n  Organization:     Google Ireland Holdings\n  ContactID:        DUP430692088\n  Address:          70 Sir John Rogersons Quay\n                    Dublin\n                    2\n                    IE\n                    IE\n  Created:          2013-04-21 01:05:35\n  Last Update:      2013-04-21 01:05:35\n\nAdmin Contact\n  Name:             Tsao Tu\n  Organization:     Tu Tsao\n  ContactID:        DUP142437129\n  Address:          70 Sir John Rogersons Quay\n                    Dublin\n                    2\n                    IE\n                    IE\n  Created:          2013-04-21 01:05:35\n  Last Update:      2013-04-21 01:05:35\n\nTechnical Contacts\n  Name:             Google Ireland Holdings\n  Organization:     Google Ireland Holdings\n  ContactID:        DUP430692088\n  Address:          70 Sir John Rogersons Quay\n                    Dublin\n                    2\n                    IE\n                    IE\n  Created:          2013-04-21 01:05:35\n  Last Update:      2013-04-21 01:05:35\n\nRegistrar\n  Organization:     MarkMonitor International Limited\n  Name:             MARKMONITOR-REG\n  Web:              https://www.markmonitor.com/\n\nNameservers\n  ns1.google.com\n  ns4.google.com\n  ns2.google.com\n  ns3.google.com\n\n'],
 'status': ['ok'],
 'updated_date': [datetime.datetime(2014, 5, 7, 0, 52, 45),
                  datetime.datetime(2013, 4, 21, 1, 5, 35)]}

**Comment by joepie91** [comment]
I can reproduce the problem. I'll get to work on fixing it straight away :)

**Comment by joepie91** [comment]
Well, that took a bit longer than expected - I had a hardware failure, and spent several hours getting everything running again... but it should be fixed now. I'll have a look at your other ticket first, before pushing an update.

**Comment by joepie91** [comment]
A new version where this is fixed (2.3.0) is now available on PyPI. Run `pip install --upgrade pythonwhois` to update. Make sure to read the [update notes](https://github.com/joepie91/python-whois#important-update-notes) prior to updating.
