### ISSUE TITLE
 python-whois can only retrieve a little information for .hk domain

### ISSUE THREAD

**Issue by holybeefy** [joepie91/python-whois#24]
Run pwhois on this domain and compare the result with this example:

http://whois.domaintools.com/unwire.hk

**Comment by joepie91** [comment]
Confirmed. Will fix this soon.

**Comment by holybeefy** [comment]
Thanks a lot!

**Comment by joepie91** [comment]
A new version where this is fixed (2.3.0) is now available on PyPI. Run `pip install --upgrade pythonwhois` to update. Make sure to read the [update notes](https://github.com/joepie91/python-whois#important-update-notes) prior to updating.
