### ISSUE TITLE
Python 3.x support?

### ISSUE THREAD

**Issue by fsufitch** [joepie91/python-whois#26]
It does not appear python-whois has Python 3.x support. As 3.x grows more commonplace, this will become a serious obstacle to adoption. 

Some problems I ran into:

```
~/python-whois$ python3 pwhois
  File "pwhois", line 6
    except ImportError, e:
                      ^
SyntaxError: invalid syntax


~/python-whois$ python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pythonwhois import get_whois
>>> get_whois('google.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fsufitch/python-whois/pythonwhois/__init__.py", line 4, in get_whois
    raw_data = net.get_whois_raw(domain)
  File "/home/fsufitch/python-whois/pythonwhois/net.py", line 15, in get_whois_raw
    domain = encode( domain if type(domain) is unicode else decode(domain, "utf8"),    "idna" )
NameError: name 'unicode' is not defined
```

There may be other problems too, but I do not have the time to conduct a code review of it right now.

Thanks for looking into this! I really wanted to use `pythonwhois` but my project is unfortunately python3-only.

**Comment by joepie91** [comment]
That's odd. The core definitely should support Python 3 - I'll have a look at why `get_whois` is failing.

`pwhois` indeed hasn't been modified to support Python 3 yet, I'll get to that in a bit.

**Comment by joepie91** [comment]
Python 3 is being particularly frustrating about strings. This is going to take a bit for me to fix.

**Comment by joepie91** [comment]
Should be fixed now. I'll be pushing a new version in a bit.

**Comment by joepie91** [comment]
A new version (2.3.0) is now available on PyPI, that carries this fix. Run `pip install --upgrade pythonwhois` to update. Make sure to read the [update notes](https://github.com/joepie91/python-whois#important-update-notes) prior to updating.

**Comment by fsufitch** [comment]
Thanks for the quick fix. Works great now.
