### ISSUE TITLE
No whois server for .moe

### ISSUE THREAD

**Issue by catatonik** [joepie91/python-whois#34]
Hi,

pwhois gives the below error when looking up .moe domains:

"No root WHOIS server found for domain."

looking at the IANA webpage for .moe, there isn't a whois server listed:

http://www.iana.org/domains/root/db/moe.html

but querying manually whois.nic.me works:

whois get.moe -h whois.nic.moe

I'm not sure if you'd add this as an exception in net.py? Not sure when/if IANA would be updated to include the correct whois server.

KR

**Comment by joepie91** [comment]
This has been fixed, and a new version incorporating this fix (2.4.3) has been released. You can upgrade using `pip install --upgrade pythonwhois`.
