### ISSUE TITLE
Add flag field for non-existent domains

### ISSUE THREAD

**Issue by chorsley** [joepie91/python-whois#41]
Suggestion: it would be useful to add rules identifying if a domain exists / is registered. Like everything, this is non-standard between TLDs:

.com.au: 'No Data Found\n'
.com: '...No match for "NOSUCHDOMAINEXAMPLE.COM"
.io: 'Domain nosuchdomainexample.io is available for purchase'

If we had a set of regexes to detect this state, and set a boolean "domain_registered" field, it would be most useful.

**Comment by joepie91** [comment]
This is a duplicate of #14. There's already some discussion going on there as to how to implement this correctly.
