### ISSUE TITLE
Decoding issues for bidtheatre.com

### ISSUE THREAD

**Issue by joepie91** [joepie91/python-whois#51]
#44 includes a fix for dealing with Unicode decoding issues, but in the case of `bidtheatre.com` (WHOIS served by "Active 24 AS", which is not correctly parsed yet), some characters still appear to be lost. This needs some looking into.

A specific source encoding may have to be used for particular WHOIS servers.

**Comment by obskyr** [comment]
I've submitted a fix for this with #59. In addition, #57 is pretty much a duplicate issue, so it should fix them both. Way better than the `errors='replace'` method, at least.

**Comment by joepie91** [comment]
I've created a new canonical thread for this in #97.
