### ISSUE TITLE
whois lookup for ASN

### ISSUE THREAD

**Issue by wallyw1** [joepie91/python-whois#70]
I can use this module to lookup ASN, but sometimes encountered errors:
(1) AS4515 - No root WHOIS server found for domain
(2) AS2706 - No root WHOIS server found for domain

Please have a look, thanks.

**Comment by joepie91** [comment]
ASNs are not currently supported by python-whois - it's really only designed for WHOISing domain names. Have you looked into whether [`ipwhois`](https://github.com/secynic/ipwhois) supports ASN lookups?

**Comment by wallyw1** [comment]
Actually I can use python-whois module to lookup most ASN except the two I mentioned, therefore I think it is supported out of box and so add this issue.

**Comment by joepie91** [comment]
Right. python-whois will connect to IANA to determine the appropriate WHOIS server for a query, so whether it "works" will depend on whether IANA has a WHOIS server to point at, and whether the WHOIS data happens to follow the same format as that of a domain registry.

That's really just an unintended side-effect of the way it works, though - ASNs are still not officially supported by python-whois, and probably won't be in the near future, as parsing ASN data is likely going to be a different challenge entirely. Right now, the focus is purely on domains, anything else is coincidental.

**Comment by wallyw1** [comment]
Thanks for your explanation.

**Comment by joepie91** [comment]
For what it's worth, [pyasn](https://pypi.python.org/pypi/pyasn) seems to do what you want.

**Comment by wallyw1** [comment]
Thanks.
