### ISSUE TITLE
No uninstall script

### ISSUE THREAD

**Issue by PidgeyL** [joepie91/python-whois#77]
Can't uninstall pythonwhois properly. Could you make an uninstall script for it, or put up some uninstall instructions?
Thanks

Pidgey@NorthernSec:~/Git/cve-search$ sudo pip uninstall pythonwhois
Can't uninstall 'pythonwhois'. No files were found to uninstall.

**Comment by fawkesley** [comment]
@PidgeyL what does `pip freeze` show? I see `pythonwhois==2.4.3`, and `pip uninstall pythonwhois` works as expected for me.

**Comment by PidgeyL** [comment]
yep, that's the version I have... not sure but now it works, before it didn't... though i use python3, pip just crashed completely
