### ISSUE TITLE
Crashes on utf-8 encoding for JSON

### ISSUE THREAD

**Issue by chb2mn** [joepie91/python-whois#88]
In command `pwhois planalto.gov.br`:

> responsible: Secretaria de Administração

crashes with the following error:

> Traceback (most recent call last):
>   File "/usr/local/bin/pwhois", line 23, in <module>
>     data, server_list = pythonwhois.net.get_whois_raw(args.domain[0], with_server_list=True)
>   File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 44, in get_whois_raw
>     response = whois_request(request_domain, target_server)
>   File "/usr/local/lib/python2.7/dist-packages/pythonwhois/net.py", line 94, in whois_request
>     return buff.decode("utf-8")
>   File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
>     return codecs.utf_8_decode(input, errors, True)
> UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 582: invalid continuation byte

**Comment by chb2mn** [comment]
`pwhois infocos.org.br` is probably a better example of this

**Comment by chb2mn** [comment]
Note: this error doesn't exist when reading in from a file, so the error lives in the way that information is taken in from the whois command

**Comment by joepie91** [comment]
I've created a new canonical thread for this in #97.
