### ISSUE TITLE
Decoder errors

### ISSUE THREAD

**Issue by guigarfr** [joepie91/python-whois#92]
Here are some errors because of the decoding, using random domains:
- eldinamo.cl: _'utf8' codec can't decode byte 0xed in position 95: invalid continuation byte_
- ziddu.com _'utf8' codec can't decode byte 0xe6 in position 3328: invalid continuation byte_
- network.hu
- biobiochile.cl _'utf8' codec can't decode byte 0xf3 in position 202: invalid continuation byte_
- primicias.cl _'utf8' codec can't decode byte 0xf1 in position 98: invalid continuation byte_

**Comment by joepie91** [comment]
I've created a new canonical thread for this in #97.
